enum CustomEventName {
  NEXT_PAGE_CLICK = 'nextPageSwitch',
  PREV_PAGE_CLICK = 'prevPageSwitch',
  CAR_CREATION_CLICK = 'carCreation',
  CAR_SELECTION_CLICK = 'carSelection',
  CAR_UPDATE_CLICK = 'carUpdate',
  RACE_START_CLICK = 'raceStart',
  RACE_RESET_CLICK = 'raceReset',
  CARS_GENERATION_CLICK = 'carsGeneration',
  CAR_START_CLICK = 'carStart',
  CAR_RESET_CLICK = 'carReset',
  CAR_REMOVE_CLICK = 'carRemove',
  PAGE_UPDATE = 'pageUpdate',
  TRACKS_REFILL = 'tracksRefill',
  ALL_CARS_START = 'allCarsStart',
  ALL_CARS_RESET = 'allCarsReset',
  CARS_UPDATE = 'carsUpdate',
  WINNERS_UPDATE = 'winnersUpdate',
  WINNER_UPDATE = 'winnerUpdate',
  WINNER_REMOVE = 'winnerRemove',
  MODAL_SHOW = 'modalShow',
  ROWS_REFILL = 'rowsRefill',
  ROWS_SORT = 'rowsSort',

  CAR_MOVEMENT_VIEW = 'carMovementView',
  CAR_STOP_VIEW = 'carStopView',
  CAR_RESET_VIEW = 'carResetView',
  CAR_SELECTION_VIEW = 'carSelectionView',
}

export default CustomEventName;
